#############################################################################
# Makefile for building: perfectParts
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon Apr 24 16:17:30 2017
# Project:  perfectParts.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile perfectParts.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DGL_GLEXT_PROTOTYPES -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_SHARED
CFLAGS        = -pipe -Qunused-arguments -I/usr/include/SDL2 -D_REENTRANT -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Qunused-arguments -msse -msse2 -msse3 -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/unsupported/linux-clang -I. -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include -Iinclude -Iimgui/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS)  -L/usr/lib64 -L/usr/X11R6/lib -lSDL2 -L/usr/local/lib -lpng -lGLU -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Window.cpp \
		src/Particle.cpp \
		src/FireworkParticle.cpp \
		src/FlameParticle.cpp \
		src/Emitter.cpp \
		src/pngutils.cpp \
		imgui/src/imgui.cpp \
		imgui/src/imgui_draw.cpp \
		imgui/src/ColourPicker.cpp \
		src/ImGUIImpl.cpp \
		src/ExplosionParticle.cpp 
OBJECTS       = main.o \
		Window.o \
		Particle.o \
		FireworkParticle.o \
		FlameParticle.o \
		Emitter.o \
		pngutils.o \
		imgui.o \
		imgui_draw.o \
		ColourPicker.o \
		ImGUIImpl.o \
		ExplosionParticle.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/clang.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/debug.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		perfectParts.pro
QMAKE_TARGET  = perfectParts
DESTDIR       = 
TARGET        = perfectParts

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: perfectParts.pro  /usr/lib64/qt4/mkspecs/unsupported/linux-clang/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/clang.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/debug.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtOpenGL.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile perfectParts.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/clang.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/debug.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtOpenGL.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile perfectParts.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/perfectParts1.0.0 || $(MKDIR) .tmp/perfectParts1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/perfectParts1.0.0/ && $(COPY_FILE) --parents include/Window.h include/Particle.h include/FireworkParticle.h include/FlameParticle.h include/Emitter.h include/ParticleType.h include/pngutils.h imgui/include/imgui.h imgui/include/stb_rect_pack.h imgui/include/stb_truetype.h imgui/include/imconfig.h imgui/include/imgui_internal.h imgui/include/stb_textedit.h include/ImGUIImpl.h include/ExplosionParticle.h .tmp/perfectParts1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Window.cpp src/Particle.cpp src/FireworkParticle.cpp src/FlameParticle.cpp src/Emitter.cpp src/pngutils.cpp imgui/src/imgui.cpp imgui/src/imgui_draw.cpp imgui/src/ColourPicker.cpp src/ImGUIImpl.cpp src/ExplosionParticle.cpp .tmp/perfectParts1.0.0/ && (cd `dirname .tmp/perfectParts1.0.0` && $(TAR) perfectParts1.0.0.tar perfectParts1.0.0 && $(COMPRESS) perfectParts1.0.0.tar) && $(MOVE) `dirname .tmp/perfectParts1.0.0`/perfectParts1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/perfectParts1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Window.o: src/Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o src/Window.cpp

Particle.o: src/Particle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particle.o src/Particle.cpp

FireworkParticle.o: src/FireworkParticle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FireworkParticle.o src/FireworkParticle.cpp

FlameParticle.o: src/FlameParticle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlameParticle.o src/FlameParticle.cpp

Emitter.o: src/Emitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Emitter.o src/Emitter.cpp

pngutils.o: src/pngutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pngutils.o src/pngutils.cpp

imgui.o: imgui/src/imgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui.o imgui/src/imgui.cpp

imgui_draw.o: imgui/src/imgui_draw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_draw.o imgui/src/imgui_draw.cpp

ColourPicker.o: imgui/src/ColourPicker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColourPicker.o imgui/src/ColourPicker.cpp

ImGUIImpl.o: src/ImGUIImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImGUIImpl.o src/ImGUIImpl.cpp

ExplosionParticle.o: src/ExplosionParticle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExplosionParticle.o src/ExplosionParticle.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

