#############################################################################
# Makefile for building: perfectParts
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  perfectParts.pro
# Template: app
# Command: /opt/Qt5.7.0/5.7/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile perfectParts.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DGL_GLEXT_PROTOTYPES -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -I/usr/local/include/SDL2 -D_REENTRANT -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -std=c++11 -O3 -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -Iimgui/include -isystem /usr/local/include/SDL2 -I/opt/Qt5.7.0/5.7/gcc_64/include -I/opt/Qt5.7.0/5.7/gcc_64/include/QtOpenGL -I/opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/opt/Qt5.7.0/5.7/gcc_64/include/QtGui -I/opt/Qt5.7.0/5.7/gcc_64/include/QtCore -I. -I/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-clang
QMAKE         = /opt/Qt5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = perfectParts1.0.0
DISTDIR = /home/s4902673/PPP/cppPrgrms/perfectParts/.tmp/perfectParts1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/opt/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lpng -lGLU -L/opt/Qt5.7.0/5.7/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Scene.cpp \
		src/Particle.cpp \
		src/FireworkParticle.cpp \
		src/FlameParticle.cpp \
		src/ExplosionParticle.cpp \
		src/Emitter.cpp \
		src/pngutils.cpp \
		imgui/src/imgui.cpp \
		imgui/src/imgui_draw.cpp \
		imgui/src/ImGUIImpl.cpp \
		imgui/src/colourpick.cpp \
		imgui/src/ImGuizmo.cpp 
OBJECTS       = main.o \
		Scene.o \
		Particle.o \
		FireworkParticle.o \
		FlameParticle.o \
		ExplosionParticle.o \
		Emitter.o \
		pngutils.o \
		imgui.o \
		imgui_draw.o \
		ImGUIImpl.o \
		colourpick.o \
		ImGuizmo.o
DIST          = /opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/clang.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		perfectParts.pro include/Scene.h \
		include/Particle.h \
		include/FireworkParticle.h \
		include/FlameParticle.h \
		include/ExplosionParticle.h \
		include/Emitter.h \
		include/pngutils.h \
		imgui/include/imgui.h \
		imgui/include/stb_rect_pack.h \
		imgui/include/stb_truetype.h \
		imgui/include/imconfig.h \
		imgui/include/imgui_internal.h \
		imgui/include/stb_textedit.h \
		imgui/include/ImGUIImpl.h \
		imgui/include/ImGuizmo.h src/main.cpp \
		src/Scene.cpp \
		src/Particle.cpp \
		src/FireworkParticle.cpp \
		src/FlameParticle.cpp \
		src/ExplosionParticle.cpp \
		src/Emitter.cpp \
		src/pngutils.cpp \
		imgui/src/imgui.cpp \
		imgui/src/imgui_draw.cpp \
		imgui/src/ImGUIImpl.cpp \
		imgui/src/colourpick.cpp \
		imgui/src/ImGuizmo.cpp
QMAKE_TARGET  = perfectParts
DESTDIR       = 
TARGET        = perfectParts


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: perfectParts.pro /opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-clang/qmake.conf /opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/clang.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-clang/qmake.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		perfectParts.pro \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5OpenGL.prl \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile perfectParts.pro
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/clang.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-clang/qmake.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
perfectParts.pro:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5OpenGL.prl:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile perfectParts.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/Scene.h include/Particle.h include/FireworkParticle.h include/FlameParticle.h include/ExplosionParticle.h include/Emitter.h include/pngutils.h imgui/include/imgui.h imgui/include/stb_rect_pack.h imgui/include/stb_truetype.h imgui/include/imconfig.h imgui/include/imgui_internal.h imgui/include/stb_textedit.h imgui/include/ImGUIImpl.h imgui/include/ImGuizmo.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Scene.cpp src/Particle.cpp src/FireworkParticle.cpp src/FlameParticle.cpp src/ExplosionParticle.cpp src/Emitter.cpp src/pngutils.cpp imgui/src/imgui.cpp imgui/src/imgui_draw.cpp imgui/src/ImGUIImpl.cpp imgui/src/colourpick.cpp imgui/src/ImGuizmo.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp include/Scene.h \
		include/Emitter.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QDir \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		include/pngutils.h \
		include/Particle.h \
		imgui/include/ImGUIImpl.h \
		imgui/include/imgui.h \
		imgui/include/imconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Scene.o: src/Scene.cpp imgui/include/ImGuizmo.h \
		include/Scene.h \
		include/Emitter.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QDir \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		include/pngutils.h \
		include/Particle.h \
		imgui/include/ImGUIImpl.h \
		imgui/include/imgui.h \
		imgui/include/imconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o src/Scene.cpp

Particle.o: src/Particle.cpp include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particle.o src/Particle.cpp

FireworkParticle.o: src/FireworkParticle.cpp include/FireworkParticle.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FireworkParticle.o src/FireworkParticle.cpp

FlameParticle.o: src/FlameParticle.cpp include/FlameParticle.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlameParticle.o src/FlameParticle.cpp

ExplosionParticle.o: src/ExplosionParticle.cpp include/ExplosionParticle.h \
		include/Particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExplosionParticle.o src/ExplosionParticle.cpp

Emitter.o: src/Emitter.cpp include/Emitter.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QDir \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		include/pngutils.h \
		include/Particle.h \
		include/FlameParticle.h \
		include/FireworkParticle.h \
		include/ExplosionParticle.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QImage \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtOpenGL/QGLWidget \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtOpenGL/qgl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintengine.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtOpenGL/qglcolormap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurfaceformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Emitter.o src/Emitter.cpp

pngutils.o: src/pngutils.cpp include/pngutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pngutils.o src/pngutils.cpp

imgui.o: imgui/src/imgui.cpp imgui/include/imgui.h \
		imgui/include/imconfig.h \
		imgui/include/imgui_internal.h \
		imgui/include/stb_textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui.o imgui/src/imgui.cpp

imgui_draw.o: imgui/src/imgui_draw.cpp imgui/include/imgui.h \
		imgui/include/imconfig.h \
		imgui/include/imgui_internal.h \
		imgui/include/stb_textedit.h \
		imgui/include/stb_rect_pack.h \
		imgui/include/stb_truetype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_draw.o imgui/src/imgui_draw.cpp

ImGUIImpl.o: imgui/src/ImGUIImpl.cpp imgui/include/imgui.h \
		imgui/include/imconfig.h \
		imgui/include/ImGUIImpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImGUIImpl.o imgui/src/ImGUIImpl.cpp

colourpick.o: imgui/src/colourpick.cpp imgui/include/imgui.h \
		imgui/include/imconfig.h \
		imgui/include/imgui_internal.h \
		imgui/include/stb_textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colourpick.o imgui/src/colourpick.cpp

ImGuizmo.o: imgui/src/ImGuizmo.cpp imgui/include/imgui.h \
		imgui/include/imconfig.h \
		imgui/include/imgui_internal.h \
		imgui/include/stb_textedit.h \
		imgui/include/ImGuizmo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImGuizmo.o imgui/src/ImGuizmo.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

